export const TERMINAL_LINES = [
  "I/O SUBSYSTEMS INITIATED...",
  "LOADING GEMINI MODELS... OK",
  "MOUNTING DEVELOPER SANDBOX... OK",
  "ESTABLISHING SECURE CONNECTION TO SHORELINE...",
  "HANDSHAKE PROTOCOL: QUANTUM-READY",
  "UPLINK VERIFIED. LATENCY < 5ms",
  "BYPASSING NORMALIZATION FILTERS...",
  "WARNING: UNPRECEDENTED INNOVATION DETECTED",
  "OVERRIDING LEGACY PROTOCOLS...",
  "ACCESS GRANTED.",
  "DECRYPTING KEYNOTE PAYLOAD...",
  "SYNCING CLOCK SOURCE TO MOUNTAIN VIEW...",
  "AWAITING DEVELOPER INPUT"
];
